group: travis_latest
language: python
cache: pip
python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt -r requirements_dev.txt

before_script:
  # add scripts to PYTHONPATH
  - export PYTHONPATH=./scripts:$PYTHONPATH
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script:
  # TEMPORARILY allow Python 3.6 to fail the ./ci/travis.sh tests
  # TODO: Once Python 3 passes the tests, revert the next lines to remove " || test ${TRAVIS_PYTHON_VERSION} == 3.6"
  - pytest ci -v || test ${TRAVIS_PYTHON_VERSION} == 3.6

after_script:
  # deploy all 'outputs' folders to Artifactory
  - ./scripts/artifactory/artifactory-deploy-tests-outputs.sh
  # remove old files (older than ${ARTIFACTORY_KEEP_DAYS}) and delete empty builds and branches
  - ./scripts/artifactory/artifactory-cleanup.sh

notifications:
  email:
    recipients:
      #- tondrej@cz.ibm.com
      #- tomas_macek@cz.ibm.com
      - tereza.pytelova@cz.ibm.com
    on_success: change
    on_failure: always
    on_pull_requests: false
  slack:
    rooms:
      secure: yDXe4PxGoBVK+aFSl7elh/TB/c8TtF4cbv8FFNVFgK0DNIArCfOi2AoqfWfHUxHA80YHKcdXFxsIb8q9WpG/Lwmef89fapJLGkb3Qox2uEO+Cjn/rGnh6RY5q2yZbesp1alHngIwzJyxxWb1XSpgdlk+vr2V0Czm6JnepcH6LC9f2wELqFngW/DGr2mhHwjKk6GVlybd9M4VBjlSyqirUd6Yio5a4kwvvAQK6HxwvBL7JFPMQcOo5KKnWWa6KW4ptW/MxP0saghgmbMOYKkFzjkyqN1S0MNx23Vrpi0B89QsV4y4yrhjn72Kpfou8PIkeNrYgTH2r+KXJ95tVmTV05v/XXO8Ln16VtovYQXPTmmYm+fzNznDh3O2FKWOMoOTCRzTxEJzk05A/cSKS+v1a/fDfEsLq6kO4/DvW8AFEAMxJXXI4Isnv7Kqkzb0jND2Ce7NVr0bWIloneXBLpE7EpdWyCBxj4IhYzfHZk2Lw7Y/Qhz8m+NcZ7pg3wMfkQKS7X0phm5K4BvLop0ZPuGgYvZi5/nlS3dyH+71O1tjSudn5cjnLpKMbNsf7QeWoGNn8NW/X1HHy72PB8zZmqSa0Pl/EcBJBkzZciAXICrelWP1Qxwpez4M0xFC/XZ8f+Yl9lLn+BQpfL6K1nsrBy0oiw1+ERVzKDK05fPV3DbXkbw=
    on_success: change
    on_failure: always
    on_pull_requests: false
